import React, { useMemo, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { StudentDetails, PaperSize, PaperType } from '../types';

interface TypedPaperProps {
  content: string;
  title?: string;
  showTitle?: boolean; 
  studentDetails?: StudentDetails | null;
  fontSize?: number;
  margins?: { top: number; bottom: number; left: number; right: number };
  lineHeight?: number;
  paperSize?: PaperSize;
  paperType?: PaperType;
  diagrams?: Record<string, string>;
  visiblePages?: number[] | 'all';
  onPageCountChange?: (count: number) => void;
  isArticle?: boolean; // NEW PROP to trigger Article Layout
}

const TypedPaper: React.FC<TypedPaperProps> = ({ 
  content, 
  title, 
  showTitle = true,
  studentDetails,
  fontSize = 16,
  margins,
  lineHeight = 28,
  paperSize = 'a4',
  paperType = 'plain',
  diagrams = {},
  visiblePages = 'all',
  onPageCountChange,
  isArticle = false
}) => {
  
  const dimensions = useMemo(() => {
    let width = 794; 
    let height = 1123;
    if (paperSize === 'letter') { width = 816; height = 1056; }
    if (paperSize === 'notebook') { width = 665; height = 945; }
    return { width, height };
  }, [paperSize]);

  const currentMargins = useMemo(() => ({
      top: margins?.top ?? 94,
      bottom: margins?.bottom ?? 25,
      left: margins?.left ?? 94,
      right: margins?.right ?? 94
  }), [margins]);

  const hasStudentDetails = useMemo(() => {
    if (!studentDetails) return false;
    const fieldsToCheck = ['name', 'instituteName', 'branch', 'semester', 'enrollmentNo', 'subjectCode'];
    return fieldsToCheck.some(field => {
        const val = (studentDetails as any)[field];
        return val && typeof val === 'string' && val.trim().length > 0;
    });
  }, [studentDetails]);

  // Extract Cover Image logic
  const { processedContent, coverImageSrc } = useMemo(() => {
    let text = content;
    let coverImg = null;

    // Regex to find image tags generated by our previous step
    // We look for the FIRST image request which is usually the cover
    const firstImageMatch = text.match(/\[DIAGRAM_ID:\s*([^\]]+)\]/);
    
    if (isArticle && firstImageMatch) {
       const idParts = firstImageMatch[1].split('|');
       const id = idParts[0].trim();
       if (diagrams && diagrams[id]) {
           coverImg = diagrams[id];
           // Remove the cover image tag from text so it doesn't appear in body
           text = text.replace(firstImageMatch[0], '');
       }
    }

    // Process remaining images
    text = text.replace(/\[DIAGRAM_ID:\s*([^\]]+)\]/g, (match, fullContent) => {
        const id = fullContent.split('|')[0].trim();
        return `\n\n![Diagram](${id})\n\n`;
    });

    return { processedContent: text, coverImageSrc: coverImg };
  }, [content, diagrams, isArticle]);

  const pages = useMemo(() => {
    if (processedContent.includes('---PAGE_BREAK---')) {
        return processedContent.split('---PAGE_BREAK---');
    }
    const chunks = [];
    
    // If Article Mode, Page 1 is reserved for Cover. 
    // We push a 'COVER_PLACEHOLDER' to the start of chunks.
    if (isArticle) {
        chunks.push('<<<COVER_PAGE>>>');
    }

    let currentChunk = '';
    const paragraphs = processedContent.split('\n');
    
    // SAFE LIMIT: 1800 chars (approx 300 words) per page to ensure fit
    const CHAR_LIMIT = 1800;

    for (const p of paragraphs) {
        if ((currentChunk + p).length > CHAR_LIMIT) { 
            chunks.push(currentChunk);
            currentChunk = p + '\n';
        } else {
            currentChunk += p + '\n';
        }
    }
    if (currentChunk) chunks.push(currentChunk);

    // If Article Mode, check if the last chunk contains "THANK YOU"
    // If so, we might want to ensure it's on a separate page or styled
    if (isArticle && currentChunk.includes('THANK YOU')) {
       // logic handled in renderer
    }

    return chunks.length > 0 ? chunks : [processedContent];
  }, [processedContent, isArticle]);

  // Report page count
  useEffect(() => {
    if (onPageCountChange) onPageCountChange(pages.length);
  }, [pages.length, onPageCountChange]);

  // RENDERER FOR COVER PAGE (Article Mode)
  const renderCoverPage = () => (
      <div className="h-full flex flex-col relative p-8">
          {/* Top Line */}
          <div className="w-full h-1 bg-slate-900 mb-6"></div>
          
          <div className="mb-6">
              <span className="text-sm font-bold uppercase tracking-widest text-slate-500 block mb-2">Article Title:</span>
              <h1 className="text-4xl font-extrabold text-slate-900 leading-tight">{title || 'Untitled Article'}</h1>
          </div>

          <div className="w-full h-px bg-slate-300 mb-6"></div>

          {studentDetails?.subjectCode && (
             <div className="mb-6">
                  <span className="text-sm font-bold uppercase tracking-widest text-slate-500 block mb-1">Subject:</span>
                  <p className="text-xl font-serif text-slate-900">{studentDetails.subjectCode}</p>
             </div>
          )}

           <div className="w-full h-px bg-slate-300 mb-8"></div>

           {/* Submitted By */}
           <div className="mb-8">
               <span className="text-sm font-bold uppercase tracking-widest text-slate-500 block mb-2">Submitted By:</span>
               <div className="grid grid-cols-1 gap-1 text-slate-900 font-medium">
                   {studentDetails?.name && <p><span className="font-bold">Name:</span> {studentDetails.name}</p>}
                   {studentDetails?.enrollmentNo && <p><span className="font-bold">Enrollment / Roll No:</span> {studentDetails.enrollmentNo}</p>}
                   {(studentDetails?.branch || studentDetails?.semester) && (
                       <p><span className="font-bold">Class & Section:</span> {studentDetails?.branch} {studentDetails?.semester ? `, ${studentDetails.semester}` : ''}</p>
                   )}
                   {studentDetails?.instituteName && <p><span className="font-bold">Department/Institution:</span> {studentDetails.instituteName}</p>}
               </div>
           </div>

           <div className="mb-6 font-bold text-slate-900">
               Session / Year: 2025–26
           </div>

           {/* Large Cover Image */}
           <div className="flex-1 w-full bg-slate-50 rounded-lg overflow-hidden relative mb-8 min-h-[300px] border border-slate-200">
                {coverImageSrc ? (
                    <img src={coverImageSrc} alt="Cover" className="w-full h-full object-cover" />
                ) : (
                    <div className="flex items-center justify-center h-full text-slate-300 font-bold text-lg uppercase tracking-widest">
                         [Cover Image]
                    </div>
                )}
           </div>

           {/* Quote */}
           <div className="text-center italic font-serif text-slate-600 text-lg">
               “Let’s learn today to protect tomorrow.”
           </div>
      </div>
  );

  const renderThankYouPage = () => (
      <div className="h-full flex flex-col items-center justify-center relative">
           <h1 className="text-5xl font-black uppercase tracking-widest text-slate-900 mb-12">Thank You</h1>
           {/* If there's a last diagram, we could show it here, but usually a simple graphic is fine */}
           <div className="w-full h-2/3 bg-cover bg-center opacity-80 rounded-xl overflow-hidden shadow-2xl" 
                style={{ backgroundImage: coverImageSrc ? `url(${coverImageSrc})` : 'none', filter: 'grayscale(20%)' }}>
                {!coverImageSrc && <div className="w-full h-full bg-slate-100 flex items-center justify-center text-slate-300">Image</div>}
           </div>
      </div>
  );

  return (
    <div className="flex flex-col gap-8 items-center w-full print:block print:gap-0">
      {pages.map((pageContent, index) => {
        // Filter Logic
        const isVisible = visiblePages === 'all' || visiblePages.includes(index + 1);
        if (!isVisible) return null;

        const isCoverPage = isArticle && pageContent === '<<<COVER_PAGE>>>';
        const isThankYouPage = isArticle && typeof pageContent === 'string' && pageContent.includes('THANK YOU') && pageContent.length < 100;

        return (
            <div key={index} id={`page-${index + 1}`} className="print:break-after-page w-full flex justify-center py-4 print:py-0 print:block">
                {/* STRICT SCALING CONTAINER - Adapted for different paper sizes */}
                <div 
                    className="relative mx-auto shadow-xl transition-all bg-white print:shadow-none print:m-0 overflow-hidden"
                    style={{
                        // Fixed dimensions for consistency
                        width: dimensions.width,
                        height: dimensions.height,
                        minHeight: dimensions.height,
                        // Scaling is handled by parent PaperContainer
                    }}
                >
                    {/* INNER SHEET */}
                    <div className="absolute top-0 left-0 origin-top-left
                        print:static print:h-auto
                        bg-white text-slate-900 font-serif
                    "
                    style={{
                        width: dimensions.width,
                        height: dimensions.height,
                        paddingTop: isCoverPage ? 0 : currentMargins.top,
                        paddingBottom: isCoverPage ? 0 : currentMargins.bottom,
                        paddingLeft: isCoverPage ? 0 : currentMargins.left,
                        paddingRight: isCoverPage ? 0 : currentMargins.right,
                        boxSizing: 'border-box',
                        backgroundColor: paperType === 'plain' ? 'white' : '#f8fafc', // Subtle bg for non-plain
                        textRendering: 'optimizeLegibility', // High quality text rendering
                        overflow: 'hidden'
                    }}>
                        
                        {/* CASE 1: ARTICLE COVER PAGE */}
                        {isCoverPage ? (
                            renderCoverPage()
                        ) : isThankYouPage ? (
                            renderThankYouPage()
                        ) : (
                            /* CASE 2: STANDARD CONTENT OR ASSIGNMENT HEADER */
                            <>
                                {index === 0 && !isArticle && (
                                    <div className={`border-b-2 border-slate-800 ${hasStudentDetails ? 'mb-8 pb-6' : 'mb-4 pb-2 border-none'}`}>
                                        {title && showTitle && (
                                            <h1 className="text-3xl font-bold text-center mb-6 uppercase tracking-wider leading-tight text-slate-900">
                                                {title}
                                            </h1>
                                        )}

                                        {hasStudentDetails && studentDetails?.instituteName && (
                                            <div className="text-center font-bold text-xl uppercase mb-6 tracking-wide text-slate-800">
                                                {studentDetails.instituteName}
                                            </div>
                                        )}

                                        {hasStudentDetails && studentDetails && (
                                            <div className="grid grid-cols-2 gap-x-8 gap-y-3 text-base font-serif mt-4 text-slate-900">
                                                {studentDetails.name && <div className="border-b border-dotted border-slate-400 pb-1"><strong>Name:</strong> {studentDetails.name}</div>}
                                                {studentDetails.enrollmentNo && <div className="border-b border-dotted border-slate-400 pb-1"><strong>Enrollment No:</strong> {studentDetails.enrollmentNo}</div>}
                                                {studentDetails.branch && <div className="border-b border-dotted border-slate-400 pb-1"><strong>Branch:</strong> {studentDetails.branch}</div>}
                                                {studentDetails.semester && <div className="border-b border-dotted border-slate-400 pb-1"><strong>Semester:</strong> {studentDetails.semester}</div>}
                                                {studentDetails.subjectCode && <div className="col-span-2 border-b border-dotted border-slate-400 pb-1"><strong>Subject Code:</strong> {studentDetails.subjectCode}</div>}
                                            </div>
                                        )}
                                    </div>
                                )}
                                
                                {index > 0 && !isCoverPage && (
                                    <div className="text-right text-sm text-slate-400 mb-8 border-b border-slate-100 pb-2">Page {index + 1}</div>
                                )}

                                <div 
                                    className={`prose prose-slate max-w-none prose-headings:font-serif prose-headings:mt-8 prose-headings:mb-4 prose-p:leading-relaxed text-slate-900 ${isArticle ? 'prose-p:text-justify prose-headings:font-bold prose-h2:text-2xl prose-h2:border-b prose-h2:border-slate-200 prose-h2:pb-2' : 'prose-p:indent-8'}`}
                                    style={{ 
                                        fontSize: `${fontSize}px`,
                                        lineHeight: `${lineHeight}px`
                                    }}
                                >
                                    <ReactMarkdown 
                                        remarkPlugins={[remarkGfm]}
                                        components={{
                                            h1: ({node, ...props}) => <h1 className="text-2xl font-bold mt-8 mb-6 border-b border-slate-300 pb-2 text-slate-900" {...props} />,
                                            h2: ({node, ...props}) => <h2 className="text-xl font-bold mt-8 mb-4 text-slate-900" {...props} />,
                                            h3: ({node, ...props}) => <h3 className="text-lg font-bold mt-6 mb-3 text-slate-900" {...props} />,
                                            p: ({node, ...props}) => <p className="mb-4 text-slate-900" {...props} />,
                                            ul: ({node, ...props}) => <ul className="list-disc pl-6 mb-4 space-y-2 text-slate-900" {...props} />,
                                            ol: ({node, ...props}) => <ol className="list-decimal pl-6 mb-4 space-y-2 text-slate-900" {...props} />,
                                            table: ({node, ...props}) => <table className="min-w-full border-collapse border border-slate-400 my-4 text-slate-900" {...props} />,
                                            thead: ({node, ...props}) => <thead className="bg-slate-100" {...props} />,
                                            th: ({node, ...props}) => <th className="border border-slate-400 px-4 py-2 font-bold text-left text-slate-900" {...props} />,
                                            td: ({node, ...props}) => <td className="border border-slate-400 px-4 py-2 text-slate-900" {...props} />,
                                            img: ({src, alt, ...props}) => {
                                                // Custom image renderer to pull from diagrams prop
                                                // The src here is the clean ID because of the regex replacement above
                                                const imgSource = (src && diagrams && diagrams[src]) ? diagrams[src] : src;
                                                return <img src={imgSource} alt={alt} className="w-full max-h-80 object-cover rounded-lg shadow-md my-8" {...props} />;
                                            }
                                        }}
                                    >
                                        {pageContent}
                                    </ReactMarkdown>
                                </div>
                            </>
                        )}
                    </div>
                </div>
            </div>
        );
      })}
    </div>
  );
};

export default TypedPaper;